server:
  port: 9002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # config necessary to locate the eureka server
      defaultZone: http://localhost:9001/eureka
